title: My First Github Pages Project
theme: minima
author: Ephrem
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first Github Pages project.

# social links
twitter_username: hooiswho # DO NOT include the @ character, or else the build will fail!
github_username:  hooiswho # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
